/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:90e7b530-6e0e-4898-8dd8-f745122c34eb",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_Eyf8WwKQO",
    "aws_user_pools_web_client_id": "7coqvidhrpq9fue6umobvs6jad",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "BIRTHDATE",
        "EMAIL",
        "FAMILY_NAME",
        "GIVEN_NAME",
        "PHONE_NUMBER"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "apic2ea3c70",
            "endpoint": "https://6f0sna6797.execute-api.us-east-2.amazonaws.com/staging",
            "region": "us-east-2"
        }
    ],
    "aws_dynamodb_all_tables_region": "us-east-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "uniouserdyn-staging",
            "region": "us-east-2"
        },
        {
            "tableName": "unioclubdyn-staging",
            "region": "us-east-2"
        }
    ]
};


export default awsmobile;
